# Site
name: "MarkDaggett.com"
title: "MarkDaggett.com"
description: "Writings, Ceramics, Code, and other distractions."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
disqus: 'markdaggettcom'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mark:
    name: Mark
    display_name: heavysixer
    gravatar: 51f10739fd903d3b57561a15e4598954
    email: me@markdaggett.com
    web: https://www.markdaggett.com
    twitter: https://twitter.com/heavysixer
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
